### ISSUE TITLE
Location Permission "Always" not shown in iOS 14 settings.

### ISSUE THREAD

**Issue by pepesrz91** [transistorsoft/react-native-background-geolocation#1168]
## Your Environment
* Plugin version: 3.9.1
* Platform: iOS
* OS version: iOS 14 and iOS 14.1
* Device manufacturer / model: iPhone 10s **( device )** and iPhone 11 Pro Max **(simulator)**
* React Native version (`react-native -v`): 0.62.0
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->

  async componentDidMount() {
    ....... 

    BackgroundGeolocation.onGeofence(this.onGeofence, this.onError);
    BackgroundGeolocation.onLocation(this.onLocation, this.onError);
    BackgroundGeolocation.onHeartbeat(this.onHeartBeat, this.onError);

    BackgroundGeolocation.ready({
      reset: true,
      debug: false,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 50,
      url: 'http://my.server.com/locations',
      autoSync: true,
      stopOnTerminate: false,
      startOnBoot: true,
    }).then(state => {
      console.log(
        '- BackgroundGeolocation is configured and ready: ',
        state.enabled,
      );

      if (!state.enabled) {
        BackgroundGeolocation.start(function() {
          console.log('- Start success');
        });
      }
    });
};
```

We set up our info.plist with the following configurations:

* Privacy - Location Always Usage Description
* Privacy - Location When In Use Usage Description 
* Privacy - Motion Usage Description
* Privacy - Location Temporary Usage Description Dictionary **(Required for precise location in iOS 14)**
* Privacy - Location Always and When in Use Usage Description

## Expected Behavior

The app must show in iOS 14 the option of allow "Always" both in the settings configuration of the app and in the second pop up of location permissions introduced in iOS 13. 

The app is working as expected in all other aspects, if we start a freeway drive, the simulator triggers the corresponding event handlers correctly when the app is in the Foreground. The same is true when using a iOS device.

## Actual Behavior

We don't get the option "Always" in settings and the second pop up requesting the user to allow location "Always" is never triggered. The app locations events are not being triggered when it is in the Background. 

## Steps to Reproduce
Just try it in an iOS 14 device. 

## Context

We want to use the geofences and location events while the app is in the background. 

We don't know if Apple has changed the actual permissions, we noticed that some location services APIs changed in both Obj-C and Swift. The best article we have found so far regarding this issue for extra context is the following:

[https://medium.com/better-programming/handling-location-permissions-in-ios-14-2cdd411d3cca](url)

Thanks for the help!

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by pepesrz91** [comment]
So we got it working 

Changed my config as example in docs:

```javascript
 BackgroundGeolocation.ready(
      {
        debug: false,
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10,
        url: 'www.example.com',
        autoSync: true,
        stopOnTerminate: false,
        startOnBoot: true,
      },
      state => {
        console.log(
          '- BackgroundGeolocation is configured and ready: ',
          state.enabled,
        );

        if (!state.enabled) {
          BackgroundGeolocation.start(function() {
            console.log('- Start success');
          });
        }
      },
    );
```

I don't think the above config caused the error, but another more subtle issue.

**[Incorrect]**: In the Info.plist we had this configuration :

![image](https://user-images.githubusercontent.com/19577959/98161706-cea09680-1ea5-11eb-92ae-4170a75ed48a.png)

If you notice, string is in a white color, meaning there is a typo in the key **Privacy - Location Always and When in Use Usage Description**

**[Correct]**: We corrected the typo ( which was a space at the end of **Privacy - Location Always and When in Use Usage Description** ), then it looks like this: 

![image](https://user-images.githubusercontent.com/19577959/98161654-ba5c9980-1ea5-11eb-8900-c6d3ebed17ab.png)

You can notice that the string character is now the same gray color as the other keys. With this change everything works as expected. A pretty dumb mistake that just wasted our time, I hope this helps to avoid anyone to have the same issue. 

**What I think is important to show is that the permission:**

* Privacy - Location Temporary Usage Description Dictionary 

Is not mentioned in the docs, and I think it is important to add that in Info.plist so that the plugin works well in iOS 14. 

Thanks to anyone who took the time in checking this out.

**Comment by stephen776** [comment]
I've got this same issue even after verifying there are no typos in my info.plist entries. (I actually had the same one you did but the issue remains after fixing)

When I start my app in the iOS simulator(iPad), I get the initial location permission prompt with the options of "allow once" or "allow while using app" which I believe is expected.

However I never get a follow up. dialog to change to "Always". Once my app starts receiving location updates, I get the following modal dialog:

![image](https://user-images.githubusercontent.com/565167/101184069-45a08a80-361e-11eb-84de-0f9e8b12260f.png)

If I cancel, my app UI appears to be locked up. components will re-render but I can't click anything as if a modal background is still blocking things.

If I choose to go Settings, the "Always" option is still not present.

**Comment by christocracy** [comment]
>Plugin version?

**Comment by stephen776** [comment]
> > Plugin version?

3.9.3

**Comment by christocracy** [comment]
iOS only allows your app to show the "Upgrade to Always" dialog once.

Go to *Settings->Privacy->Location Services->Your app* and reset to `[Ask Next time]`.

**Comment by stephen776** [comment]
When I change the the setting to Ask Next Time and re-launch the app, I get the permissions dialog as expected (see below)
![image](https://user-images.githubusercontent.com/565167/101187859-e4c78100-3622-11eb-9a3c-378f5348b237.png)

But after that, I get no second dialog re: the "always" permissions and I get the "Background location is not enabled" shotly after

**Comment by christocracy** [comment]
Try installing the [SampleApp](https://github.com/transistorsoft/rn-background-geolocation-demo) on your device.

**Comment by stephen776** [comment]
The sample app seems to work fine. I get the "always" prompt almost immediately after the initial prompt

**Comment by stephen776** [comment]
Ok, I figured it out. I compared the Info.plist from my app and sample and I was missing:

```<key>NSLocationTemporaryUsageDescriptionDictionary</key>
	<dict>
		<key>DemoPurpose</key>
		<string>CHANGEME:  Allow the sample app to track location with high accuracy</string>
	</dict>```

This appears to be important for showing the secondary "always" modal
